JuliaDocs/DocumentationGenerator.jl

landingpage/package-lock.json
landingpage/package.json
landingpage/vue.config.js

Ref https://github.com/JuliaLang/julia/issues/31622.
Thanks @zxj5470!

compress blobs

---

.travis.yml
Project.toml
src/worker_work.jl

- Reopening as this was not part of https://github.com/JuliaDocs/DocumentationGenerator.jl/commit/6186847fe7f0e9dc0e90a1270dcc14e00ed7bc8b

License detection

---

landingpage/src/App.vue
landingpage/src/components/CodefilterCard.vue

* Fix appending `.jl` to `julia` search results
* some refactoring

Handle Search result links for Julia+Base

---

landingpage/babel.config.js
landingpage/package.json
landingpage/src/App.vue
landingpage/src/components/PackageCard.vue
landingpage/vue.config.js

ie11 compat

---

src/worker_work.jl

https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/54 doesn't fix the issue

Update: Store Package owner value without auth

---

src/DocumentationGenerator.jl

* Handle scenarios where `SIGTERM` is blocked/ignored/handled by the process

Force kill stuck processes

---

landingpage/src/App.vue

Additional filters enabled in UI to call symbol search and also includes a bug fix for search UI being freezed out while handling certain responses.

More filters for symbol search

---

src/DocumentationGenerator.jl
src/worker_work.jl

set documentationgenerator specific env vars

---

Project.toml
src/DocumentationGenerator.jl
test/runtests.jl

instead of the commonmarker ruby gem

use githubmarkdown.jl

---

src/utils/pkgtools.jl
test/runtests.jl

strings instead of symbols in dicts

---

src/builders.jl
src/rundocumenter.jl

and fix a bug when no make.jl file is found

better logs

---

src/DocumentationGenerator.jl
src/workerfile.jl
test/runtests.jl

```
build
├── DifferentialEquations
│   └── UQdwS
│       ├── 6.9.0
│       └── 6.9.0.log
├── DynamicHMC
│   └── iPqvI
│       ├── 2.1.1
│       └── 2.1.1.log
├── Example
│   └── lLvWP
│       ├── 0.5.1
│       ├── 0.5.1.log
│       ├── 0.5.3
│       └── 0.5.3.log
```

better log file location

---

src/workerfile.jl
test/runtests.jl

fix for weird version specifiers

---

src/DocumentationGenerator.jl
src/builders.jl
src/workerfile.jl
test/runtests.jl

plus some more error handling for weird corner cases

make sure buildpath always exists

---

src/utils/rewrite.jl
test/runtests.jl

fix `fix_makefile` for `make(;...)` syntax

---

src/utils/runners.jl

Fixes https://github.com/JuliaDocs/DocumentationGenerator.jl/issues/148. Timeout is set to 3hrs by default.

max time for runners

---

Project.toml

Update compat versions for some of the dependencies.
Also bumped the package patch version for tagging.

Update package compat versions in Project.toml

---

.github/workflows/CI.yml
src/DocumentationGenerator.jl
src/utils/pkgtools.jl

fixes failures due to https://github.com/JuliaRegistries/General/pull/79064

fix: read registry's package path as per the Registry.toml

---

run/makedocs.jl
src/utils/pkgtools.jl
test/runtests.jl

it would be nice filter deps and reversedeps by registry

Tag registry name to deps and reverse deps

---

.github/workflows/CI.yml
src/DocumentationGenerator.jl
src/builders.jl

broken https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/196

fix: docgen fails for versions < 1.9

---

Project.toml
src/builders.jl

broken by https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/202

Fix: undefvar Documenter

---

src/utils/rewrite.jl

fixes https://github.com/JuliaDocs/DocumentationGenerator.jl/issues/208
Works for older versions of Documenter as well

fix: documenter 1.0 remote issue

---

Project.toml
src/builders.jl

Use AbstractTrees 0.4

---

.github/workflows/CI.yml
Project.toml
src/builders.jl
src/utils/rewrite.jl
test/runtests.jl

Rewrite `makedocs` also if it's not on top-level
