.travis.yml, README.md, src/DocumentationGenerator.jl, src/worker_work.jl, test/runtests.jl
By using ~~redcarpet~~ commonmarker to render gfm-compatible markdown (for readme docs). 
~~This doesn't quite work yet because I can't figure out how to tell redcarpet to use gfm.~~
Fixes https://github.com/JuliaDocs/DocumentationGenerator.jl/issues/19.
=> WIP: better readme rendering

src/worker_work.jl
* Store owner in meta.toml even when git auth fails
=> Store Package owner value even if github auth fails

src/DocumentationGenerator.jl, src/worker_work.jl, test/.gitignore, test/runtests.jl
With this PR package authors can specify how and where their docs are in https://github.com/JuliaDocs/DocumentationGeneratorRegistry.
=> Allow specifying doctype in registry

src/DocumentationGenerator.jl
=> pipe through arguments to `Documenter.HTML()`

src/DocumentationGenerator.jl
- occurs when main process's environment is not DocumentationGenerator's base environment.
=> Fix: Unable to load deps on subprocesses

src/utils/runners.jl
- fix termination of generation for https://juliahub.com/ui/Packages/GeophysicalFlows/xFqhg/0.4.3
=> increase run timeout to 40 min

src/metadata.jl
Alternative to `DOCGEN_GITHUB_AUTH_FILE`, set the token directly as env variable
=>  Add DOCGEN_GITHUB_AUTH_TOKEN to set GitHub token 

src/DocumentationGenerator.jl, src/metadata.jl
- Caller should be able to retry metadata fetch based on the exception
- fixes: pkgeval data parsing issue change in index type(package `uuid` to `name`)
=> Add ability to inspect exception if fetching repo metadata fails

src/rundocumenter.jl
to give a clean namespace for user provided expression
=> fix: eval into module

src/builders.jl, test/runtests.jl
- removed Octo.jl (doesn't have Project.toml in docs directory which is indicative of legacy Documenter, so we pin Documenter to 0.20, which doesn't work if absent in the depot). 
- removed Electron.jl since it takes 60 min to complete
- fixed ReactionNetworkImporter test to reflect addition to DocumentationGeneratorRegistry
- fix URL redirect error when relative path is specified in `meta`
=> Fix the CI

.github/workflows/CI.yml, src/DocumentationGenerator.jl, src/builders.jl
Since we are unlikely load the packages again
=> fix: turn off pkgimages during generation

Project.toml, src/rundocumenter.jl, test/runtests.jl
Following #184 we evaluate the `make.jl` script into a temporary module, but Documenter generally assumes that things are present in `Main` (e.g. when referring to them in at-meta blocks). This flips the `rundocumenter.jl` script around, putting all our code into an anonymous module, but `@eval`-ing the updated `make.jl` expression into `Main`. Fix #199.
cc @vdayanand @pfitzseb
=> Run Documenter in Main

src/builders.jl, test/runtests.jl
It looks like we're automatically pulling in Documenter 1.0 with these lines, and this is now causing, at least, test failures: https://github.com/JuliaDocs/DocumentationGenerator.jl/actions/runs/6183787531/job/16911998356
I am not 100% sure why the readme build would fail with Documenter 1.0 at the moment, but I suspect it's because of AbstractTrees incompatibility (#180). But regardless -- it should not be necessary to reinstall Documenter in this eval, since it already exists in the DocumentationGenerator environment.
=> fix: don't re-install Documenter in main environment

src/builders.jl
Currently, in the auto-generated fallback docs, we don't pick up docstrings from submodules. E.g.: https://juliahub.com/ui/Code/docs/Pluto/OJqMt/0.19.22.log#L135
This is because we only give the at-autodocs block the top level module, but you need to list each module the explicitly. This patch is a proof of concept example of how we could fix that (I haven't run the code actually).
This relies on an internal Documenter function,`Documenter.submodules`, which lives [here](https://github.com/JuliaDocs/Documenter.jl/blob/b50d74bc02d6883ef36aa19f19129e7a2d675ea9/src/utilities/utilities.jl#L220-L241). I believe the Documenter module is, in principle, accessible. But we could also copy the implementation here.
=> Pick up docstrings from submodules in fallback docs

src/DocumentationGenerator.jl, src/registry.jl
Adds a logic where it tries to clone the registry first from
- `https://github.com/JuliaComputing/DocumentationGeneratorRegistry.git`
and if that fails, it clones from the current
- `https://github.com/JuliaDocs/DocumentationGeneratorRegistry.git`
Currently, looks like this when run:
```
julia> DocumentationGenerator.get_registry(pwd())
Cloning into '/tmp/jl_UF11kJ/registry'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
┌ Warning: Unable to clone DocumentationGeneratorRegistry
│   registry = "https://github.com/JuliaComputing/DocumentationGeneratorRegistry.git"
│   exception =
│    failed process: Process(setenv(`/usr/bin/git clone --depth=1 https://github.com/JuliaComputing/DocumentationGeneratorRegistry.git /tmp/jl_UF11kJ/registry`,[...]), …
```
=> Support registry hosted under JuliaComputing

src/registry.jl
Trivial follow-up to #213: it just occurred to me that it would make more sense if it prefers JuliaDocs on the 0.7 branch. I.e it will first try to clone from JuliaDocs, and if that fails, it goes to JuliaComputing. This means:
* Before the move, the first attempt will succeed, so it behaves like before.
* After the move, it will likely also just keep working.
* But if cloning from JuliaDocs no longer works, then it will clone from JuliaComputing and still keep working.
In 0.8, which we'll tag after the move, we can either change it around again, or remove JuliaDocs altogether.
=> Prefer JuliaDocs registry in 0.7, but fall back to JuliaComputing

Project.toml, src/DocumentationGenerator.jl
- worker process will only have the packages which it needs rather inheriting the top level project
- Long term fix: refactor workerfile to not depend on DocumentationGenerator
=> Run worker project in isolated environment

Project.toml, src/utils/rewrite.jl, test/runtests.jl
After #216, we're setting the `remotes` keyword to `nothing`. But if the user's `make.jl` sets the `repo`, then we'll fail to generate the documentation with:
```
ERROR: LoadError: 
ArgumentError: When `remotes` is set to `nothing`, `repo` must not be set.
```
So this also enforces the `repo = ""` default, to ensure that the documentation builds don't fail.
=> fix: also unset `repo` in the packages `make.jl`

src/utils/runners.jl
IOBuffer alias has changed in 1.11 (`Base.GenericIOBuffer{Array{UInt8, 1}}` -> `Base.GenericIOBuffer{GenericMemory{:not_atomic, UInt8, Core.AddrSpace{Core}(0x00)}}`)
=> fix: methoderror while reading process output

src/DocumentationGenerator.jl, src/utils/runners.jl, test/runtests.jl
Currently, children processes (spawn by packages) don't kill after timeout. This PR uses process [group](https://www.man7.org/linux/man-pages/man2/setpgid.2.html) to kill them. 
Alternative to https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/231
=> fix: child processes are not killed after timeout

src/builders.jl, test/runtests.jl
Fixes https://github.com/JuliaDocs/DocumentationGenerator.jl/issues/234.
=> fix: add warnonly=true for readme autodocs

Project.toml, test/runtests.jl
To patch https://github.com/JuliaComputing/HTMLSanitizer.jl/security/advisories/GHSA-3mj7-qxh9-6q4p.
=> chore: update HTMLSanitizer
